In [12]:
import numpy as np
import random
import pandas as pd

from typing import Callable
import time 
from datetime import datetime as dt

import itertools


In [ ]:
def create_game_combos(seq_len: int=3) -> list:
    '''
    Use to initialize all possible Penney's games scenarios where sequences are a given length, 
    excluding matchups between 2 equal sequence choices.

    Arguments:
        seq_len: The number of elements per sequence that the players choose to scan for
    
    Returns:
        combinations: 3D list of (2^seq_len)^2-(2^seq_len) tuples of length 2, each tuple length seq_len 
    '''
    p1 = list(itertools.product([0,1], repeat=seq_len))
    p2 = list(itertools.product([0,1], repeat=seq_len))
    combinations = [(x, y) for x in p1 for y in p2 if x!=y]

    return(combinations)

In [13]:
# Code adapted from student Yueran Shi
def get_init_deck(half_deck_size: int) -> np.ndarray:
    """Generate an initial deck with equal 0s and 1s."""
    return np.array([0] * half_deck_size + [1] * half_deck_size)
    
def get_n_decks(n_decks: int, half_num_cards: int) -> tuple[np.ndarray, np.ndarray]:
    """
    Efficiently generate `n_decks` shuffled decks using NumPy.
    
    Returns:
        decks (np.ndarray): 2D array of shape (n_decks, half_num_cards), each row is a shuffled deck.
        seeds (np.ndarray): 1D array of seeds used for shuffling.
    """
    init_deck = get_init_deck(half_num_cards)  # Base deck
    decks = np.tile(init_deck, (n_decks, 1))  # Create a 2D array of identical decks
    seeds = np.arange(n_decks)  # Use seed values from 0 to n_decks-1
    
    for i, seed in enumerate(seeds):
        np.random.seed(seed)
        np.random.shuffle(decks[i])  # Shuffle each row with a different seed
    
    return decks, seeds

'''
# Example usage
decks, seeds = get_n_decks(1000000)  # Generate 1,000,000 decks efficiently
print(decks[0:5])  
print(seeds[0:5])
'''

'\n# Example usage\ndecks, seeds = get_n_decks(1000000)  # Generate 1,000,000 decks efficiently\nprint(decks[0:5])  \nprint(seeds[0:5])\n'

In [ ]:
# Example implementation
all_combos=create_game_combos(seq_len = 3)
all_combos[0:10]

[((0, 0, 0), (0, 0, 1)),
 ((0, 0, 0), (0, 1, 0)),
 ((0, 0, 0), (0, 1, 1)),
 ((0, 0, 0), (1, 0, 0)),
 ((0, 0, 0), (1, 0, 1)),
 ((0, 0, 0), (1, 1, 0)),
 ((0, 0, 0), (1, 1, 1)),
 ((0, 0, 1), (0, 0, 0)),
 ((0, 0, 1), (0, 1, 0)),
 ((0, 0, 1), (0, 1, 1))]

In [34]:
HALF_DECK_SIZE = 5
decks, seeds = get_n_decks(n_decks = 5, half_num_cards = HALF_DECK_SIZE)
print(decks[0:5])  
print(seeds[0:5])

[[0 1 0 1 0 1 1 0 0 1]
 [0 1 1 0 0 0 0 1 1 1]
 [0 0 1 0 1 0 0 1 1 1]
 [1 0 0 0 1 1 1 0 0 1]
 [0 1 0 1 0 1 0 0 1 1]]
[0 1 2 3 4]
